spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb"
  profiles:
    include: api-key, oauth